Update api CD.yml

diff --git a/.github/workflows/api CD.yml b/.github/workflows/api CD.yml
--- a/.github/workflows/api CD.yml
+++ b/.github/workflows/api CD.yml
@@ -24,4 +24,11 @@ jobs:
           cd BackEnd
           git pull
           killall python3
+          if [ $? -eq 0 ]; then
+            echo "Process killed successfully."
+          else
+            echo "Error: Failed to kill the process."
+            exit 1
+          fi
+            
           python main.py          
